### ISSUE TITLE
Unexpected dense task placement for k8s cluster

### ISSUE THREAD

**Issue by dalanlan** [camsas/poseidon#2]
Hi, I was running a containerized poseidon with camsas/poseidon:dev on the master node of a k8s cluster. Yet since it was properly brought up (or at least that's what I thought), it cannot help scheduling every pod onto the master node (`10.10.103.67` in this case, as you could see in the log) while the  other two worker nodes are completely lack of workload. The three machines involved are homogeneous.

> Note that the first busybox is scheduled by kube-scheduler.

I was wondering if I should *bring up another two poseidon instances* to make things right ( 'cause seems that we should bring up a Firmament coordinator on every worker node of the cluster) or, it's just some kind of *coincidence* and everything is taken care of?

cc @ms705 Appreciate your help in advance.

```
root@ubuntu:~# kubectl get nodes
NAME           STATUS    AGE
10.10.103.67   Ready     4d
10.10.103.68   Ready     4d
10.10.103.69   Ready     4d
root@ubuntu:~# kubectl get pods -o wide
NAME                            READY     STATUS    RESTARTS   AGE       IP           NODE
busybox                         1/1       Running   96         4d        10.1.82.2    10.10.103.69
busybox-trident-basic           1/1       Running   25         1d        10.1.34.5    10.10.103.67
busybox-trident-basic-1         1/1       Running   0          38m       10.1.34.6    10.10.103.67
frontend-3223876880-1rl4q       1/1       Running   0          9m        10.1.34.7    10.10.103.67
frontend-3223876880-fof79       1/1       Running   0          9m        10.1.34.8    10.10.103.67
frontend-3223876880-rg3mi       1/1       Running   0          9m        10.1.34.9    10.10.103.67
redis-master-3804387969-ot2z9   1/1       Running   0          9m        10.1.34.10   10.10.103.67
redis-slave-368277221-nwkye     1/1       Running   0          9m        10.1.34.11   10.10.103.67
redis-slave-368277221-pgh1p     1/1       Running   0          9m        10.1.34.12   10.10.103.67

```

**Comment by dalanlan** [comment]
Sorry again that I am being vague here. The example pods I am trying to run are from k8s doc[https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook]. They r not computation or I/O sensitive to me, no, but I just want to make sure it's not like the case that poseidon *cannot* see other options but the machine resource it runs on.

**Comment by ms705** [comment]
@dalanlan This is entirely plausible: depending on the value of `--max_tasks_per_pu` that you use (the default is 10), the scheduler may put several pods on each machine.

The specific policy applied depends on what cost model the Firmament library uses under the hood. This is read from [the `--flow_scheduling_cost_model` flag](https://github.com/camsas/firmament/blob/master/src/scheduling/flow/flow_scheduler.cc#L47-L50) and the default is the `TRIVIAL` cost model (0). The trivial cost model does not have any sophisticated assignment policy: it just sets a higher cost for leaving tasks unscheduled than for scheduling them anywhere. If you want to look into using more complex policies with Poseidon, you'll want to specify a different cost model. That said: since Poseidon does not yet allow for passing K8s metrics through to Firmament's knowledge base, the policies will have little information to work with, and may not do anything particularly useful when using from Poseidon.

Depending on what your goal is, you could either patch Poseidon with the necessary plumbing to get your cost model to work (we can possibly help you with this), or you could develop your own cost model that reflects the scheduling policy you need (again, we can help with this, but it will require building the Firmament library (and Poseidon) from scratch.

**Comment by ms705** [comment]
Closing, as things have moved on (although above still remains essentially valid).

Let us know if any questions remain, or if you encounter issues with the new code.
